apiVersion: jib/v1alpha1
kind: BuildFile

from:
  image: adoptopenjdk:8-jre

entrypoint: ["/script.sh"]

layers:
  entries:
    - name: scripts
      files:
        - properties:
            filePermissions: 755
          src: script.sh
          dest: /script.sh
